# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='art_category',
            field=models.IntegerField(choices=[(1, 'Name_Portraits'), (2, 'Dictionary_Prints'), (3, 'Quote_Prints')], default=1),
        ),
    ]
